### ISSUE TITLE
No text for "Adding Variations to Existing Songs"

### ISSUE THREAD

**Issue by VMan-2002** [FunkinCrew/funkin-modding-docs#17]
The absence of [this page](https://funkincrew.github.io/funkin-modding-docs/02-custom-songs-and-custom-levels/02-05-adding-variations-to-existing-songs.html)'s content is kicking my ass :(

**Comment by EliteMasterEric** [comment]
I didn't end up writing that page is why. Good to know people want it though.

**Comment by VMan-2002** [comment]
pog

**Comment by NotHyper-474** [comment]
This page has just been updated: https://github.com/FunkinCrew/funkin-modding-docs/commit/3b2b1b4adde4d2e9b4249b65fa6a1cd5da8f2b59

**Comment by VMan-2002** [comment]
hell yeah 🥳 thank u a lot
only remaining bit i see currently is that
```
{
    { "op": "add", "path": "/playData/songVariations/-", "value": "erect" }, // Add a new value erect to the end of the songVariations array.
}
```
should be
```
[
    { "op": "add", "path": "/playData/songVariations/-", "value": "erect" } // Add a new value erect to the end of the songVariations array.
]
```
(with square brackets, and without the last comma)
but thank u very much this is very helpful

**Comment by VMan-2002** [comment]
https://github.com/FunkinCrew/funkin-modding-docs/pull/18
