### ISSUE TITLE
The links in the readme don't work

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/funkin-modding-docs#4]
They all lead to the wrong path, directories back from the src directory at least -- I have personally tested them all myself. ~Has someone changed the file structure without changing the readme~ (UPDATE: I can confirm this is the issue, the entire file structure is different and has a toml thing and I don't know why. The src files are all in different pages. If you're doing a restructure you shouldn't just not document it at all and actively do it through commits to the main branch.)~?~ I remember these working not long ago.

**Comment by EliteMasterEric** [comment]
The links in the readme have been removed and replaced with the new github.io link, which displays the docs as a clean webpage.
