### ISSUE TITLE
Enhancement: Add "healthicon" field from character JSONs to the documentation (and the respective format of the health icon field)

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/funkin-modding-docs#9]
It's not good to leave things like this undocumented. It's misleading if you're saying that those are the available fields. Only documenting the fields from the example you put there is not the way to go, if that's what you did.

**Comment by anysad** [comment]
Will be fixed in #11 once merged.

**Comment by biomseed** [comment]
> merged
